self-hosted-runner:
  labels:
    - oracle-vm-2cpu-8gb-x86-64
    - oracle-vm-4cpu-16gb-x86-64
    - oracle-vm-8cpu-32gb-x86-64
    - oracle-vm-16cpu-64gb-x86-64
    - oracle-vm-24cpu-96gb-x86-64
    - oracle-vm-32cpu-128gb-x86-64
